# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Code\Python\cupat\static\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 494)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Code\\Python\\cupat\\static\\ui\\../static/icons/index.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.rootWidget = QtWidgets.QWidget(MainWindow)
        self.rootWidget.setObjectName("rootWidget")
        self.mainWindowWidgetGridLayout = QtWidgets.QGridLayout(self.rootWidget)
        self.mainWindowWidgetGridLayout.setObjectName("mainWindowWidgetGridLayout")
        MainWindow.setCentralWidget(self.rootWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cupat"))
